### ISSUE TITLE
[tracking] Model and Op Support

### ISSUE THREAD

**Issue by stellaraccident** [nod-ai/SHARK-Turbine#119]
Tracking model burndown for Gen-AI models and variants that we seek to be serving via Turbine.

- [ ] Dynamic shaped llama2
  - [x] #153
  - [ ] Int4 Quantization with parameters from llama.cpp
  - [ ] Meeting latency requirements
- [ ] SHARK Model Porting
  - [ ] #152 (@aviator19941 )
    - [x] Unet
    - [x] VAE
    - [x] CLIP
    - [ ] Controlnet support (@gpetters94 )
    - [ ] LoRA support
  - [ ] https://github.com/nod-ai/SHARK/issues/1931 (@monorimet )
  - [ ] SHARK TANK -- in progress: https://github.com/nod-ai/SHARK/pull/1904 (@monorimet )

- [ ] Priority op requests
  - [ ] #210
  - [x] #110  @AmosLewis 
  
  - [ ] OPS to linalg in llama_test when https://github.com/nod-ai/SHARK-Turbine/pull/212:
    - [ ] torch.aten.empty_strided 
    - [ ] torch.aten.mean.dim
    - [ ] torch.aten.expand 
    - [ ] torch.aten._softmax
    - [ ] torch.aten.silu 

- [ ] General torch-mlir op support
  - [ ] torch.aten.kthvalue
  - [ ] torch.aten._fft_c2c
  - [ ] torch.aten.fmod.Tensor
  - [ ] torch.aten.affine_grid_generator
  - [ ] torch.aten._fft_c2r
  - [ ] torch.aten.histc
  - [ ] torch.aten.poisson
  - [ ] torch.aten.logit
  - [ ] torch.aten._linalg_solve_ex
  - [ ] torch.aten._pdist_forward
  - [ ] torch.aten.linalg_cholesky_ex
  - [ ] torch.aten.triu_indices
  - [ ] torch.aten.lgamma
  - [ ] torch.aten.prod
  - [ ] torch.aten.all.dim
  - [ ] torch.aten.resize_as
  - [ ] torch.aten._cdist_forward
  - [ ] torch.aten._sample_dirichlet
  - [ ] torch.aten.remainder.Tensor
  - [ ] torch.aten._sparse_addmm
  - [ ] torch.aten.cosh
  - [ ] torch.aten.renorm
  - [ ] torch.aten.diagonal
  - [ ] torch.aten.tril_indices
  - [ ] torch.aten.upsample_trilinear3d
  - [ ] torch.aten.linalg_cross
  - [ ] torch.aten.pixel_unshuffle
  - [ ] torch.aten.rrelu_with_noise
  - [ ] #160
  - [ ] torch.aten._sparse_coo_tensor_with_dims_and_tensors
  - [ ] torch.aten.lerp.Scalar
  - [ ] torch.aten.trace
  - [ ] torch.aten.normal.float_float
  - [ ] torch.aten.hann_window.periodic
  - [ ] torch.aten._adaptive_avg_pool3d
  - [ ] torch.aten.resize
  - [ ] torch.aten.normal.Tensor_Tensor
  - [ ] torch.aten.unfold
  - [ ] #231
  - [ ] torch.aten.conv_tbc
  - [ ] torch.aten.norm.Scalar
  - [ ] torch.aten._fft_r2c
  - [ ] torch.aten._linalg_slogdet
  - [ ] torch.aten.prod.dim_int
  - [ ] torch.aten._trilinear
  - [ ] torch.aten.as_strided
  - [ ] #293 
  - [ ] torch.aten.exponential
  - [ ] torch.aten.randperm
  - [ ] torch.aten.min.dim
  - [ ] torch.aten.argmin
  - [ ] torch.aten.replication_pad3d
  - [ ] torch.aten.acos
  - [ ] #288
  - [ ] torch.aten.max_unpool2d
  - [ ] #163
  - [x] #161
  - [ ] #286
  - [ ] #159
  - [ ] torch.aten.normal_functional
  - [ ] torch.aten.max_pool3d_with_indices
  - [ ] #148
  - [ ] torch.aten._weight_norm_interface
  - [ ] torch.aten.reflection_pad2d 

- [ ] ONNX op support
https://github.com/nod-ai/SHARK-Turbine/issues/215

**Comment by newling** [comment]
@stellaraccident in meeting chat:

If you are actively working on one, please click the "target" hover to the right of any task to create an issue. Then assign yourself. Note the issue in PRs. Discuss prioritization on the tracking issue and details of the op on the op issue.

**Comment by newling** [comment]
This is a list of ops that @saienduri gathered  (in increasing order of appearance, i.e. **later ops more important**) from parity-bench (I think using https://github.com/nod-ai/SHARK-Turbine/blob/main/tests/generated/running_tests.md): 

torch.aten.kthvalue
torch.aten._fft_c2c
torch.aten.fmod.Tensor
torch.aten.affine_grid_generator
torch.aten._fft_c2r
torch.aten.histc
torch.aten.poisson
torch.aten.logit
torch.aten._linalg_solve_ex
torch.aten._pdist_forward
torch.aten.linalg_cholesky_ex
torch.aten.triu_indices
torch.aten.lgamma
torch.aten.prod
torch.aten.all.dim
torch.aten.resize_as
torch.aten._cdist_forward
torch.aten._sample_dirichlet
torch.aten.remainder.Tensor
torch.aten._sparse_addmm
torch.aten.cosh
torch.aten.renorm
torch.aten.diagonal
torch.aten.tril_indices
torch.aten.upsample_trilinear3d
torch.aten.linalg_cross
torch.aten.pixel_unshuffle
torch.aten.rrelu_with_noise
torch.aten.adaptive_max_pool3d
torch.aten._sparse_coo_tensor_with_dims_and_tensors
torch.aten.lerp.Scalar
torch.aten.trace
torch.aten.normal.float_float
torch.aten.hann_window.periodic
torch.aten._adaptive_avg_pool3d
torch.aten.resize
torch.aten.normal.Tensor_Tensor
torch.aten.unfold
torch.aten.isinf
torch.aten.conv_tbc
torch.aten.norm.Scalar
torch.aten._fft_r2c
torch.aten._linalg_slogdet
torch.aten.prod.dim_int
torch.aten._trilinear
torch.aten.as_strided
torch.aten.reflection_pad1d
torch.aten.exponential
torch.aten.randperm
torch.aten.min.dim
torch.aten.argmin
torch.aten.replication_pad3d
torch.aten.acos
torch.aten.diag_embed
torch.aten.max_unpool2d
torch.aten.avg_pool3d
torch.aten.glu
torch.aten.replication_pad2d
torch.aten.adaptive_max_pool2d
torch.aten.normal_functional
torch.aten.max_pool3d_with_indices
torch.aten.pixel_shuffle
torch.aten._weight_norm_interface
torch.aten.reflection_pad2d

Someone on the call today also mentioned pixel_shuffle as an important op to support.

**Comment by newling** [comment]
@stellaraccident I'm not sure I've done what you had in mind - I created a new issue by clicking "New issue" (top right of this page, for me at least). I don't seem to have permission to assign myself to it though

**Comment by stellaraccident** [comment]
You should now have an invite to the organization and I think I added you to a team such that you have write access to the repo.

**Comment by lisaliu1** [comment]
@stellaraccident I plan to implemente torch.aten.replication_pad2d op, and created the following issue for that. But I cannot link the op to the created issue. Maybe I missed something.
https://github.com/nod-ai/SHARK-Turbine/issues/286

**Comment by schnkmwt** [comment]
Opened a issue tracker for the op torch.aten.diag_embed. @stellaraccident Can you help link it from the list above?
https://github.com/nod-ai/SHARK-Turbine/issues/288

**Comment by schnkmwt** [comment]
@kumardeepakamd I think this op is already being implemented: https://github.com/llvm/torch-mlir/issues/2604

**Comment by AmosLewis** [comment]
**For ALL new contributors**, let's use this to track your newly implemented ops. [tracking] TorchToLinalg and ONNX Op Support #215

**Comment by AmosLewis** [comment]
Close this issue temporarily so we focus on #215 .
