### ISSUE TITLE
[tracking] Quantization Integration

### ISSUE THREAD

**Issue by stellaraccident** [nod-ai/SHARK-Turbine#120]
Turbine aims to support integration with multiple quantization workflows, generally meeting model development where it is at on a case by case basis.

- [ ] Ad-hoc quantization via AOT transforms and weight import (built-out in the context of llama2)
- [ ] AutoGPTQ Integration (built out in the context of Falcon180B)
- [ ] General floating point type demotion and fine tuning
