### ISSUE TITLE
[tracking] CI and Testing

### ISSUE THREAD

**Issue by stellaraccident** [nod-ai/SHARK-Turbine#122]
We are generally aiming to have the Turbine model garden serve as a test suite for both changes to this project and able to be used in upstream IREE / SRT. It should have both a quick and a full version.

- [ ] Quick/smoke full model tests on CPU gates submission to Turbine
- [ ] Scheduled/nightly full model tests on Turbine
- [ ] Upstream IREE job to run quick tests as part of presubmit in PkgCI on supported archs
- [ ] Upstream IREE job to run full tests as part of a scheduled job based on PkgCI for supported arches
- [ ]
