### ISSUE TITLE
[tracking] Upstreaming

### ISSUE THREAD

**Issue by stellaraccident** [nod-ai/SHARK-Turbine#123]
In many ways, Turbine is a feature driver for upstream projects. We aim to upstream in a timely fashion.

- [ ] [https://discourse.llvm.org/t/torch-mlir-pytorch2-uplift/74000/13](Torch-MLIR PyTorch2 Uplift)
- [ ] Upstream `importer.py` to torch-mlir post uplift
- [ ] Add `importer.py` to IREE as part of its torch-mlir integration and port Turbine to use it
- [ ] Upstream IREE `util.global` enhancements to reach parity with MLIR `ml_program.global`
  - [ ] AsmInterface SSA values should derive from the symbol name
  - [ ] `noinline` attribute should be preserved in IREE `ml_program` lowering
  - [ ] Parameter attributes should be preserved in IREE `ml_program` lowering
  - [ ] Rework Turbine to use `ml_program` globals internally instead of `util.global`
  - [ ] Investigate whether rework of globals creates additional upstreaming opportunities
