### ISSUE TITLE
[tracking] Documentation And Samples

### ISSUE THREAD

**Issue by stellaraccident** [nod-ai/SHARK-Turbine#124]
User documentation and samples need to be enhanced. Depending on context, these can either by in Turbine itself or in IREE (i.e. colab notebookes, etc). In either case, documentation cross-referencing should be in place.

## Documentation:

- [ ] Overall developer orientation (e.g. https://discord.com/channels/689900678990135345/908461811026767952/1168632460842651701)
- [ ] Procedural / `CompiledModule` programmers guide (see for inspiration: https://github.com/iree-org/iree-jax#iree-jax-api)

## Samples:

- [ ] Meaningful dynamic shapes sample
  - [ ] Fix torch-mlir view op legalization issues (#115)
  - [ ] Enable `mlir_export_dynamic.py`
