### ISSUE TITLE
[tracking] TorchToLinalg Op Support

### ISSUE THREAD

**Issue by vivekkhandelwal1** [nod-ai/SHARK-Turbine#347]
EDIT: ANYONE WORKING ON THE OP PLEASE CREATE AN ISSUE AS SOON AS YOU START WORKING ON THE OP TO AVOID CLASHES.

Contact: @vivekkhandelwal1 in the Indian time zone and @AmosLewis in the US time zone. 
For more discussion, please check and ask in discord [LLVM/torch-mlir](https://discord.gg/btswZzPTVW) channel. 

Tracking op support for TorchToLinalg lowering. The ops are ordered based on priority (highest -> lowest) in each section.

- [ ] General torch-mlir op support
  - [ ] #337
  - [ ] torch.aten._weight_norm_interface
  - [x] torch.aten.pixel_shuffle (completed in #2590)
  - [ ] torch.aten.max_pool3d_with_indices
  - [ ] #326
  - [ ] #159
  - [ ] #286 
  - [x] torch.aten.glu
  - [ ] #300
  - [ ] torch.aten.max_unpool2d
  - [ ] #288 
  - [x] #338
  - [ ] #305
  - [x] #339
  - [x] #340
  - [ ] torch.aten.randperm
  - [x] #341
  - [x] #293 
  - [ ] torch.aten.as_strided
  - [ ] torch.aten._trilinear
  - [ ] torch.aten.prod.dim_int
  - [ ] torch.aten._linalg_slogdet
  - [ ] torch.aten._fft_r2c
  - [ ] torch.aten.norm.Scalar
  - [ ] torch.aten.conv_tbc #345 
  - [x] torch.aten.isinf
  - [ ] torch.aten.unfold
  - [ ] torch.aten.normal.Tensor_Tensor
  - [ ] torch.aten.resize
  - [ ] torch.aten._adaptive_avg_pool3d
  - [ ] torch.aten.hann_window.periodic
  - [x] #343
  - [ ] #333
  - [ ] torch.aten.lerp.Scalar
  - [ ] torch.aten._sparse_coo_tensor_with_dims_and_tensors
  - [x] torch.aten.adaptive_max_pool3d
  - [ ] torch.aten.rrelu_with_noise
  - [ ] torch.aten.pixel_unshuffle
  - [ ] torch.aten.linalg_cross
  - [ ] torch.aten.upsample_trilinear3d
  - [ ] torch.aten.tril_indices
  - [ ] #297
  - [ ] torch.aten.renorm
  - [x] #342
  - [ ] torch.aten._sparse_addmm
  - [ ] torch.aten.remainder.Tensor
  - [ ] torch.aten._sample_dirichlet
  - [ ] torch.aten._cdist_forward
  - [ ] torch.aten.resize_as
  - [ ] torch.aten.all.dim
  - [x] torch.aten.prod
  - [ ] torch.aten.lgamma https://github.com/nod-ai/SHARK-Turbine/issues/317
  - [ ] torch.aten.triu_indices
  - [ ] torch.aten.linalg_cholesky_ex
  - [ ] torch.aten._pdist_forward
  - [ ] torch.aten._linalg_solve_ex
  - [ ] https://github.com/nod-ai/SHARK-Turbine/issues/290
  - [ ] torch.aten.poisson
  - [ ] torch.aten.histctorch.aten.affine_grid_generator
  - [ ] torch.aten.fmod.Tensor
  - [ ] torch.aten._fft_c2c
  - [ ] torch.aten.kthvalue

**Comment by jinchen62** [comment]
@vivekkhandelwal1 According to the triage of iree onnx tests failures, these ops are missing TorchToLinalg lowering. Please add them to the above list.

To reproduce issue:
build venv following https://github.com/nod-ai/SHARK-TestSuite/tree/main/iree_tests#common-venv-setup-with-deps
run `iree-compile iree_tests/onnx/node/generated/TEST_NAME/model.mlir -o test.vmfb --iree-hal-target-backends=llvm-cpu --mlir-print-ir-after-all`

- [ ] torch.aten.cumsum
  - test_cumsum_1d
  - test_cumsum_2d_axis_0
  - test_cumsum_2d_axis_1
  - test_cumsum_2d_negative_axis
- [ ] torch.aten.nonzero
  - test_nonzero_example

**Comment by lingzhiz1998** [comment]
Hi, can I take torch.aten.max_pool3d_with_indices op task?

**Comment by lingzhiz1998** [comment]
Attach this PR https://github.com/llvm/torch-mlir/pull/3652 to mark max_pool3d_with_indices as in progress. I can not change the status of task list.

**Comment by vivekkhandelwal1** [comment]
> Attach this PR [llvm/torch-mlir#3652](https://github.com/llvm/torch-mlir/pull/3652) to mark max_pool3d_with_indices as in progress. I can not change the status of task list.

Done
