### ISSUE TITLE
Fast Llama2 on W7900/RDNA Tracker

### ISSUE THREAD

**Issue by raikonenfnu** [nod-ai/SHARK-Turbine#485]
Task list required to achieve good performance on RDNA GPUs:

- [ ]  Add Cooperative matrix support for Dequant-Matmul (In Progress - raikonenfnu)
- [ ] Add dynamic padding support to guarantee Coop Matrix shapes (TODO - unassigned)
- [ ] Add fused attention support and pipeline for VK through Coop matrix. (TODO - unassigned)
- [ ] Fine tuning performance for prefill llama2-7b (TODO - unassigned)
- [ ] Fine tuning performance for prefill llama2-70b (TODO - unassigned)
- [ ] Fine tuning performance for decode llama2-7b  (TODO - unassigned)
- [ ] Fine tuning performance for decode llama2-70b  (TODO - unassigned)
