### ISSUE TITLE
turbine-models: consolidate sd and sdxl implementations.

### ISSUE THREAD

**Issue by monorimet** [nod-ai/SHARK-Turbine#608]
Since SDXL is sufficiently different in model architecture from SD1.5/2.0, their implementations in turbine-models are nearly entirely separate from each other. Now that the implementation for SDXL has been completed, we see opportunities to couple the two implementations where applicable.

The largest tasks in this consolidation are as follows:

- [ ] use diffusers configs for models where applicable to decide shapes for inference tasks -- nothing hardcoded i.e. max length, embeddings shape, hidden dim, etc. This helps us parametrize code that can be agnostic of SD model architecture.
- [ ] use one pipeline with different "model mappings" for stable diffusion model architectures
- [ ] Organize torch model definitions and compiled module definitions and keep them decoupled from pipelines, runners, utils.
- [ ] restructure sd_inference/sdxl_inference into one directory
