### ISSUE TITLE
[tracking] HF CNN fp32 model tests

### ISSUE THREAD

**Issue by jinchen62** [nod-ai/SHARK-Turbine#801]
Below is the list of HF CNN fp32 model issues for 500 models out of 530.

### **model-run**

- [ ] ONNXRuntimeError ([30 models](https://gist.github.com/jinchen62/1b23c9c227b772c7e7641fad39aa6ea9))

### **torch-mlir**

- [ ] onnx.AveragePool ([5 models](https://gist.github.com/jinchen62/3ef667ee61425e2f3a0bea77c78d10db))
- [ ] onnx.BatchNormalization ([61 models](https://gist.github.com/jinchen62/d896ffb09a95146d55354b297ea25ad7))
- [ ] onnx.Conv ([10 models](https://gist.github.com/jinchen62/b8afb5aea091e83ee93c4a92a5061380))
- [ ] onnx.LSTM ([1 model](https://gist.github.com/jinchen62/8b064acd647be39a29c65632dd17d5e2))
- [ ] onnx.Split crash ([6 models](https://gist.github.com/jinchen62/aa8fb97cf74ef6fb96a82afea78d0216))
- [ ] onnx.Transpose ([280 models](https://gist.github.com/jinchen62/513efb16979805092962ddc10c523223))
- [ ] killed ([8 models](https://gist.github.com/jinchen62/d91ee55e641e35deca13b344bb3c2eeb))

`onnx.BatchNormalization`, `onnx.Conv`, `onnx.LSTM` are mentioned in https://github.com/nod-ai/SHARK-Turbine/issues/566.

### **iree-compile**

- [ ] integer value too large ([40 models](https://gist.github.com/jinchen62/dd477d02e9e40630eaa3f00e816be464))

### **inference**

- [ ] mismatch ([73 models](https://gist.github.com/jinchen62/c870373258c5a1c71c975f81258463de))

**Comment by jinchen62** [comment]
Model tests are imported in https://github.com/nod-ai/SHARK-TestSuite/pull/313.

**Comment by AmosLewis** [comment]
onnx.Conv in #566 has been fixed by disable quantized 1d conv. This should be a different conv error.

**Comment by AmosLewis** [comment]
Better to add the failed op into https://github.com/nod-ai/SHARK-Turbine/issues/797

**Comment by AmosLewis** [comment]
onnx.Batchnorm in https://github.com/nod-ai/SHARK-Turbine/issues/566 also has been fixed by bump iree. This should be a different error. Maybe you should check vivek's patch https://github.com/llvm/torch-mlir/pull/3597

**Comment by vivekkhandelwal1** [comment]
Hi @jinchen62, can you please update this issue, since it seems some of these have been fixed.

**Comment by jinchen62** [comment]
@vivekkhandelwal1 Nothing was changed by Monday, will verify and update weekly.
